name: flutter_animated_login
description: "A new Flutter package project."
version: 0.0.1
homepage: https://example.com

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.2.0
  material_loading_buttons: ^1.2.1
  pinput: ^4.0.0
  toastification: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: null
